### ISSUE TITLE
case insensitive comparison

### ISSUE THREAD

**Issue by davidress-ILW** [wjbmattingly/ww2-spacy#5] opened 2023-08-17 18:49 UTC
This is an awesome repo!

Just a comment really, but it does not perform case insensitive comparisons; for example, 'Sherman' is found but 'sherman' is not. Do you have any suggestions for making the comparisons case insensitive?

Again, this is a great repo. Thank you.

**Comment by wjbmattingly** [comment] 2023-08-17 19:24
Thanks so much! I am happy to hear you are enjoying the library. I am actually about to revisit this library next week. This is something I could implement. I kept it case-sensitive by design, but I think you are quite right. Sherman could likely appear either way in texts, as could other vehicles like it. My thinking behind keeping it case sensitive were for other vehicles like panther, tiger, etc. I will make a PR next week to add an option to turn on case insensitivity. It requires adjusting the rules in the entity_ruler from TEXT to LOWER when it looks for matches at the token level.

**Comment by wjbmattingly** [comment] 2023-09-13 17:34
Sorry this took so long. I have a working solution, but it will be part of my adjacent library [Bagpipes SpaCy](https://github.com/wjbmattingly/bagpipes-spacy) which provides a suit of utils components for problems like this. I'll update here when it is fully included there. Once it is, I'll add it as a pipe in this pipeline and you can activate/deactivate it as necessary. It will be deactivated by default. For now, if you want to use it, you can add this into your own script. This is the the component and it shows you how to use it. The final version will likely be a class where a user can specify which ruler they want to add case insensitivity to.


```python
import spacy
from spacy.language import Language

@Language.component("case_ruler")
def case_ruler(doc):
    ruler = nlp.get_pipe("entity_ruler")
    # Check if patterns have already been modified
    if not getattr(ruler, "_case_insensitive_modified", False):
        new_patterns = []
        
        for pattern in ruler.patterns:
            label = pattern["label"]
            new_pattern = {"label": label, "pattern": []}
            
            for token_spec in pattern["pattern"]:
                if "LOWER" not in token_spec:
                    token_spec["LOWER"] = token_spec.pop("TEXT", "").lower()
                new_pattern["pattern"].append(token_spec)
            
            new_patterns.append(new_pattern)
        nlp.remove_pipe("entity_ruler")
        # Create a new EntityRuler with the modified patterns
        new_ruler = nlp.add_pipe("entity_ruler")
        new_ruler.add_patterns(new_patterns)
        new_ruler._case_insensitive_modified = True
        return nlp(doc.text)

    return doc


nlp = spacy.blank("en")

# Add the original entity ruler to the pipeline
ruler = nlp.add_pipe("entity_ruler")

# Add patterns
patterns = [{"label": "Tank", "pattern": [{"TEXT": "Sherman"}, {"TEXT": "Tank"}]}]
ruler.add_patterns(patterns)

# Add the custom function to the pipeline
nlp.add_pipe("case_ruler", before="entity_ruler")

# Process text
doc = nlp("I love sherman tank and SHERMAN TANK. Sherman Tank.")
for ent in doc.ents:
    print(ent.text, ent.label_)
```

**Comment by davidress-ILW** [comment] 2024-05-24 13:23
Great work! Thank you so much for adding case insensitive comparisons.

**Closed as completed** 2024-05-24 13:23 UTC
